import { expect, test, _electron as electron } from '@playwright/test';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
test('API settings save large budgets, validate ranges and survive reopening', async () => {
  test.setTimeout(120000);
  const temp = await fs.mkdtemp(path.join(os.tmpdir(), 'novel-api-preferences-'));
  const app = await electron.launch({ ...(process.env.NOVEL_COMPILER_PACKAGED_EXE ? { executablePath: path.resolve(process.env.NOVEL_COMPILER_PACKAGED_EXE) } : { args: [path.resolve('.')] }), env: { ...process.env, NODE_ENV: 'test', NOVEL_COMPILER_USER_DATA: path.join(temp, 'data') } });
  try {
    const page = await app.firstWindow();
    const errors: string[] = []; page.on('pageerror', e => errors.push(e.message));
    await expect(page.locator('.world-library')).toBeVisible();
    await app.evaluate(({ dialog }, directory) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [directory] }); }, temp);
    await page.evaluate(() => window.novelCompiler.createProject('参数检查工程'));
    await page.reload();
    await page.locator('.library-enter').click();
    await page.getByRole('button', { name: '进入编译工作台' }).click();
    await page.getByRole('button', { name: 'API 设置' }).click();
    await expect(page.getByLabel('分析输出上限（Token）', { exact: true })).toHaveValue('6000');
    await page.getByLabel('自定义服务商名称', { exact: true }).fill('Local Mock');
    await page.getByLabel('API 基础地址', { exact: true }).fill('https://mock.invalid/v1');
    await page.getByLabel('API 密钥', { exact: true }).fill('test-only-not-a-real-key');
    await page.getByLabel('全局默认模型', { exact: true }).fill('mock-model');
    await page.getByLabel('分析输出上限（Token）', { exact: true }).fill('65536');
    await expect(page.getByRole('button', { name: '安全保存', exact: true })).toBeDisabled();
    await page.getByLabel('截断重试上限（Token）', { exact: true }).fill('131072');
    await page.getByLabel('试聊输出上限（Token）', { exact: true }).fill('4096');
    await page.getByLabel('单次请求超时（秒）', { exact: true }).fill('600');
    await page.getByLabel('分析温度 Temperature', { exact: true }).fill('0.2');
    await page.getByLabel('最大尝试次数（含首次）', { exact: true }).fill('2');
    await page.getByLabel('核心目标（字符）', { exact: true }).fill('4000');
    await page.getByRole('button', { name: '安全保存', exact: true }).click();
    await expect.poll(() => page.evaluate(async () => (await window.novelCompiler.getApiStatus()).requestSettings?.jsonMaxTokens)).toBe(65536);
    await expect(page.getByLabel('API 密钥', { exact: true })).toHaveValue('');
    await page.getByRole('button', { name: '工程总览' }).click();
    await page.getByRole('button', { name: 'API 设置' }).click();
    await expect(page.getByLabel('分析输出上限（Token）', { exact: true })).toHaveValue('65536');
    await expect(page.getByLabel('截断重试上限（Token）', { exact: true })).toHaveValue('131072');
    await expect(page.getByLabel('核心目标（字符）', { exact: true })).toHaveValue('4000');
    await expect(page.getByLabel('分析温度 Temperature', { exact: true })).toHaveValue('0.2');
    await page.getByLabel('分析输出上限（Token）', { exact: true }).scrollIntoViewIfNeeded();
    await fs.mkdir('verification-results/api-settings-integrated8', { recursive: true });
    await page.screenshot({ path: 'verification-results/api-settings-integrated8/01-output-settings.png', animations: 'disabled' });
    await page.getByRole('button', { name: '恢复参数默认值', exact: true }).click();
    await expect(page.getByLabel('分析输出上限（Token）', { exact: true })).toHaveValue('6000');
    expect((await page.evaluate(() => window.novelCompiler.getApiStatus())).requestSettings?.jsonMaxTokens).toBe(65536);
    await page.getByLabel('自定义服务商名称', { exact: true }).fill('BUPT');
    await page.getByLabel('API 基础地址', { exact: true }).fill('https://myai.bupt.edu.cn/llm-gw/v1');
    await page.locator('.settings-form input[type=password]').fill('isolated-mock-key');
    await page.getByLabel('全局默认模型', { exact: true }).fill('DeepSeek V4 Flash');
    await page.getByRole('button', { name: '安全保存', exact: true }).click();
    await expect.poll(() => page.evaluate(async () => (await window.novelCompiler.getApiStatus()).preferredModel)).toBe('deepseek-v4-flash');
    expect(errors).toEqual([]);
  } finally { await app.close(); await fs.rm(temp, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); }
});
